# Generated by Django 2.2.19 on 2022-01-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_auto_20220121_2024"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group", old_name="address", new_name="slug",
        ),
        migrations.RenameField(model_name="group", old_name="name", new_name="title",),
    ]
